config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: [:index, :new, :create, :show] do
    resources :binges, only: [:index, :new, :create]
  end

  resources :media
  

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/binge.rb
class Binge < ApplicationRecord
  STATUS = [ "geschaut", "nicht geschaut" ]
  enum :status, STATUS
  belongs_to :user
  belongs_to :medium

  def users
    medium.binges.map(&:user)
  end

  def friends(user)
    friends_array = users
    friends_array.delete(user)
    friends_array
  end
end

app/models/medium.rb
class Medium < ApplicationRecord
  has_many :binges, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email,
            # :name,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: URI::MailTo::EMAIL_REGEXP } # <-- validates that the email is in correct format, and that it is unique

  
  validates :name,
            presence: true

  has_many :binges, dependent: :destroy  
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate

  private

  def authenticate
    user = authenticate_with_http_basic do |email, p|
      User.authenticate_by(email: email, password: p)
    end

    if user
      @current_user = user
    else
      request_http_basic_authentication
    end
  end
end

app/controllers/binges_controller.rb
class BingesController < ApplicationController
  def index
    @user = User.find(params[:user_id]) #man kann andere User anschauen
    @binges = @user.binges.includes(:medium)
    @friends = User.where
  end

  def new
    @user = @current_user
    @binge = Binge.new
    @media = Medium.all
  end

  def create
    @user = @current_user
    @binge = @user.binges.new(binge_params)

    if @binge.save
      redirect_to user_binges_path(@user), notice: "Serie wurde hinzugefügt!"
    else
      @medium = Medium.all
      render :new
    end
  end

  private

  def binge_params
    params.require(:binge).permit(:medium_id, :status)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to user_binges_path(@current_user)
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
    before_action :set_medium, only: %i[ show edit update destroy ]

  def index
    @media = Medium.all
  end

  def show
  end

  def new
    @media = Medium.new
  end

  def create
    @media = Medium.new(medium_params)
    if @media.save
      redirect_to @media
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @media.update(medium_params)
      redirect_to @media
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @media.destroy
    redirect_to media_path
  end

  private

  def set_medium
    @media = Medium.find(params[:id])
  end

  def medium_params
    params.expect(medium: [ :name ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_binges_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.expect(user: [ :name, :email, :password ])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/binges/index.html.erb
<h1>Hallo <%= @user.name%> diese Medien hast du alle gesehen! </h1>

<%= link_to "Neue Serie hinzufügen", new_user_binge_path(@user) %>

<ul>
  <% @binges.each do |binge| %>
    <li>
      <strong><%= binge.user.name %></strong> hat 
      <em><%= binge.medium.name %> <%= binge.status %></em> - <%= binge.friends(binge.user).map(&:name).uniq.join(", ") %>.
    </li>
  <% end %>
</ul>

<p>
<%= link_to "Medien", media_path %>
</p>

<%= link_to "Users", users_path%>

app/views/binges/new.html.erb
<h1>Serie als geschaut markieren</h1>

<%= form_with model: [@user, @binge], local: true do |form| %>
  <div>
    <%= form.label :medium_id, "Serie auswählen" %><br>
    <%= form.collection_select :medium_id, @media, :id, :name, prompt: "Bitte Serie auswählen" %>
  </div>

   <div>
    <%= form.label :status, "Status" %><br>
<%= form.select :status, Binge::STATUS, prompt: "Bitte Status auswählen" %> 
  </div>

  <div>
    <%= form.submit "Speichern" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Serienapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/media/_form.html.erb
<%= form_with model: medium do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/media/edit.html.erb
<h1>Edit Medium</h1>

<%= render "form", medium: @media %>
<%= link_to "Cancel", @media %>

app/views/media/index.html.erb
<h1>Media</h1>

<%= link_to "New medium", new_medium_path %>

<ul>
  <% @media.each do |medium| %>
    <li>
      <%= link_to medium.name, medium %>
    </li>
  <% end %>
</ul>

<p>
  <%= link_to "Users", users_path%>
  </p>

app/views/media/new.html.erb
<h1>New medium</h1>

<%= render "form", medium: @media %>

app/views/media/show.html.erb
<h1><%= @media.name %></h1>


<%= link_to "Back", media_path %>

<%= link_to "Edit", edit_medium_path(@media) %>

<%= button_to "Delete", @media, method: :delete, data: { turbo_confirm: "Are you sure?" } %>

app/views/users/index.html.erb
<h1>Users</h1>

<p>
  <% @users.each do |user| %>
    <li>
      <strong><%= link_to user.name, user_binges_path(user) %></strong> 
    </li>
  <% end %>
</p>

<%= link_to "New User", new_user_path %> 

app/views/users/new.html.erb
<h1>New product</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password %>  
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>